spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9ebdd4c5e3e6a2d8e8c7
            clientSecret: 24158fae623984440efbd6e56cf32413b44f5b68
          google:
            clientId: 695596589328-4gsiv915dv2qjemduoaghdj1db65sn4k.apps.googleusercontent.com
            clientSecret: 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

